name: Integration Actions to Build Custom Image

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  action_on_pull_request_merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.ENV_PORT }}
      DB_NAME: ${{ secrets.POSTGRES_DB }}
      DB_USER: ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      HOST: ${{ vars.HOST}}
      DIALECT: ${{vars.DIALECT}}
      LINK_EXPIRATION_TIME: ${{vars.LINK_EXPIRATION_TIME}}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      ZONE: ${{vars.ZONE}}
      SOURCE_IMAGE_FAMILY: ${{ vars.SOURCE_IMAGE_FAMILY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      DISK_SIZE: ${{ vars.DISK_SIZE}}
      DISK_TYPE: ${{ vars.DISK_TYPE }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.IAM_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Create Zip File of Webapp Repo
        run: |
          zip -r webapp.zip .

      - name: Move Zip to Workflows Directory
        run: mv webapp.zip vm-image/

      - name: Init and Build Custom Image
        run: |
          cd vm-image/
          packer init gcpBuild.pkr.hcl
         
      - name: Create new Instance Template version
        run: |
          TEMPLATE_NAME="web-instance-template-v2"
          gcloud compute instance-templates create $TEMPLATE_NAME --project=csye6225-a03 --description=This\ template\ is\ used\ to\ create\ web\ instances\ depending\ on\ the\ load --machine-type=e2-standard-2 --network-interface=network-tier=STANDARD,subnet=webapp --instance-template-region=us-east4  --region=us-east4 --metadata=startup-script=\#\!/bin/bash$'\n'$'\n'cd\ /home/Cloud/webapp/\ \|\|\ exit$'\n'$'\n'env_values=\$\(cat\ \<\<EOF$'\n'PORT=3001$'\n'DB_NAME=webapp$'\n'DB_USER=webapp$'\n'DB_PASSWORD=ewpnkOJ8KqVZlFiN$'\n'HOST=10.188.112.2$'\n'DIALECT=postgres$'\n'NODE_ENV=PROD$'\n'LINK_EXPIRATION_TIME=120$'\n'EOF$'\n'\)$'\n'echo\ \"\$env_values\"\ \|\ sudo\ tee\ .env\ \>/dev/null$'\n'sudo\ chown\ csye6225:csye6225\ .env\ $'\n'echo\ \".env\ file\ created\"$'\n'$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=service-account-webapp@csye6225-a03.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write --tags=web-instance --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=csye6225-1712532924,kms-key=projects/csye6225-a03/locations/us-east4/keyRings/regional_keyring/cryptoKeys/vm_instance_key,mode=rw,size=100,type=pd-standard --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

      - name: Configure Managed Instance Group to Use the New Template
        run: |
         TEMPLATE_NAME="web-instance-template-v2"
         gcloud compute instance-groups managed set-instance-template webapp-instance-group-manager --template=https://www.googleapis.com/compute/v1/projects/csye6225-a03/regions/us-east4/instanceTemplates/$TEMPLATE_NAME --region=us-east4 

      - name: Recreate Instances in Managed Instance Group
        run: gcloud compute instance-groups managed rolling-action replace webapp-instance-group-manager --max-unavailable=2 --region=us-east4  

      - name: Wait for Instance Group Refresh
        run: gcloud compute instance-groups managed wait-until --stable webapp-instance-group-manager --region=us-east4 




