name: Integration Actions to Build Custom Image

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  action_on_pull_request_merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.ENV_PORT }}
      DB_NAME: ${{ secrets.POSTGRES_DB }}
      DB_USER: ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      HOST: ${{ vars.HOST}}
      DIALECT: ${{vars.DIALECT}}
      LINK_EXPIRATION_TIME: ${{vars.LINK_EXPIRATION_TIME}}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{vars.REGION}}
      ZONE: ${{vars.ZONE}}
      SOURCE_IMAGE_FAMILY: ${{ vars.SOURCE_IMAGE_FAMILY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      DISK_SIZE: ${{ vars.DISK_SIZE}}
      DISK_TYPE: ${{ vars.DISK_TYPE }}8
      TEMPLATE_NAME: ${{vars.INSTANCE_TEMPLATE_NAME}}
      NETWORK_INTERFACE_TIER: ${{vars.NETWORK_INTERFACE_TIER}} 
      SUBNET: ${{vars.SUBNET}}
      KEYRING_NAME: ${{vars.KEYRING_NAME}}
      MIG: ${{vars.MIG}}
      MIG_INSTANCE_TEMPLATE_PATH: ${{vars.MIG_INSTANCE_TEMPLATE_PATH}}
      MAX_INSTANCE_UNAVAILABLE: ${{vars.MAX_INSTANCE_UNAVAILABLE}}
      MACHINE_TYPE: ${{vars.MACHINE_TYPE}}
      INSTANCE_DB_HOST: ${{ vars.INSTANCE_DB_HOST}}
      INSTANCE_DB_PASSWORD: ${{vars.INSTANCE_DB_PASSWORD}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.IAM_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Create Zip File of Webapp Repo
        run: zip -r webapp.zip .

      - name: Move Zip to Workflows Directory
        run: mv webapp.zip vm-image/

      - name: Init and Build Custom Image
        run: |
          cd vm-image/
          packer init gcpBuild.pkr.hcl
         
      # - name: Create new Instance Template version
      #   run: gcloud compute instance-templates create $TEMPLATE_NAME --project=$PROJECT_ID --description=This\ template\ is\ used\ to\ create\ web\ instances\ depending\ on\ the\ load --machine-type=$MACHINE_TYPE --network-interface=network-tier=$NETWORK_INTERFACE_TIER,subnet=$SUBNET --instance-template-region=$REGION  --region=$REGION --metadata=startup-script=\#\!/bin/bash$'\n'$'\n'cd\ /home/Cloud/webapp/\ \|\|\ exit$'\n'$'\n'env_values=\$\(cat\ \<\<EOF$'\n'PORT=$PORT'\n'DB_NAME=$DB_NAME'\n'DB_USER=$DB_USER'\n'DB_PASSWORD=$INSTANCE_DB_PASSWORD'\n'HOST=$INSTANCE_DB_HOST'\n'DIALECT=$DIALECT'\n'NODE_ENV=PROD$'\n'LINK_EXPIRATION_TIME=$LINK_EXPIRATION_TIME'\n'EOF$'\n'\)$'\n'echo\ \"\$env_values\"\ \|\ sudo\ tee\ .env\ \>/dev/null$'\n'sudo\ chown\ csye6225:csye6225\ .env\ $'\n'echo\ \".env\ file\ created\"$'\n'$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=service-account-webapp@csye6225-a03.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write --tags=web-instance --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=csye6225-1712532924,kms-key=projects/$PROJECT_ID/locations/$REGION/keyRings/$KEYRING_NAME/cryptoKeys/vm_instance_key,mode=rw,size=$DISK_SIZE,type=pd-standard --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --reservation-affinity=any

      # - name: Configure Managed Instance Group to Use the New Template
      #   run:  gcloud compute instance-groups managed set-instance-template $MIG --template=$MIG_INSTANCE_TEMPLATE_PATH/$TEMPLATE_NAME --region=$REGION 

      # - name: Recreate Instances in Managed Instance Group
      #   run: gcloud compute instance-groups managed rolling-action replace $MIG --max-unavailable=$MAX_INSTANCE_UNAVAILABLE --region=$REGION  

      # - name: Wait for Instance Group Refresh
      #   run: gcloud compute instance-groups managed wait-until --stable $MIG --region=$REGION

      - name: Create new Instance Template version
        run: gcloud compute instances create web-instance-$TEMPLATE_NAME--project=csye6225-a03 --zone=us-east4-c --description=This\ template\ is\ used\ to\ create\ web\ instances\ depending\ on\ the\ load --machine-type=e2-standard-2 --network-interface=network-tier=STANDARD,stack-type=IPV4_ONLY,subnet=webapp --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default --metadata=startup-script=\#\!/bin/bash$'\n'$'\n'cd\ /home/Cloud/webapp/\ \|\|\ exit$'\n'$'\n'env_values=\$\(cat\ \<\<EOF$'\n'PORT=3001$'\n'DB_NAME=webapp$'\n'DB_USER=webapp$'\n'DB_PASSWORD=UAsaVuoaMkuzB02R$'\n'HOST=10.199.202.2$'\n'DIALECT=postgres$'\n'NODE_ENV=PROD$'\n'LINK_EXPIRATION_TIME=120$'\n'EOF$'\n'\)$'\n'echo\ \"\$env_values\"\ \|\ sudo\ tee\ .env\ \>/dev/null$'\n'sudo\ chown\ csye6225:csye6225\ .env\ $'\n'echo\ \".env\ file\ created\"$'\n'$'\n' --maintenance-policy=MIGRATE --provisioning-model=STANDARD --service-account=service-account-webapp@csye6225-a03.iam.gserviceaccount.com --scopes=https://www.googleapis.com/auth/pubsub,https://www.googleapis.com/auth/logging.write,https://www.googleapis.com/auth/monitoring.write --tags=web-instance --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/debian-cloud/global/images/debian-12-bookworm-v20240312,kms-key=projects/csye6225-a03/locations/us-east4/keyRings/regional_keyring/cryptoKeys/vm_instance_key,mode=rw,size=10,type=projects/csye6225-a03/zones/us-east4-c/diskTypes/pd-standard --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring --labels=goog-ec-src=vm_add-gcloud --reservation-affinity=any

      - name: Configure Managed Instance Group to Use the New Template
        run:  gcloud compute instance-groups managed set-instance-template webapp-instance-group-manager --template=https://www.googleapis.com/compute/v1/projects/csye6225-a03/regions/us-east4/instanceTemplates/$TEMPLATE_NAME --region=us-east4 

      - name: Recreate Instances in Managed Instance Group
        run: gcloud compute instance-groups managed rolling-action replace webapp-instance-group-manager --max-unavailable=1 --region=us-east4  

      - name: Wait for Instance Group Refresh
        run: gcloud compute instance-groups managed wait-until --stable webapp-instance-group-manager --region=us-east4 