name: Integration Actions to Build Custom Image

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  action_on_pull_request_merge:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.ENV_PORT }}
      DB_NAME: ${{ secrets.POSTGRES_DB }}
      DB_USER: ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      HOST: ${{ vars.HOST}}
      DIALECT: ${{vars.DIALECT}}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      ZONE: ${{vars.ZONE}}
      SOURCE_IMAGE_FAMILY: ${{ vars.SOURCE_IMAGE_FAMILY }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      DISK_SIZE: ${{ vars.DISK_SIZE}}
      DISK_TYPE: ${{ vars.DISK_TYPE }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: GCP Authentication
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.IAM_SERVICE_ACCOUNT }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Use gcloud CLI
        run: "gcloud info"

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Create Zip File of Webapp Repo
        run: |
          zip -r webapp.zip .

      - name: Move Zip to Workflows Directory
        run: mv webapp.zip vm-image/

      - name: Init and Build Custom Image
        run: |
          cd vm-image/
          packer init gcpBuild.pkr.hcl
          packer build gcpBuild.pkr.hcl
