name: Packer Continuous Integration Actions to Build custom image

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  packer_template_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Format Packer Configs
        run: |
          cd vm-image/
          packer fmt gcpBuild.pkr.hcl

      - name: Validate Packer Configs
        run: |
          cd vm-image/
          packer validate gcpBuild.pkr.hcl
