name: Integration Test for User APIs

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: Run integration tests for users
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create test database and user
        run: |
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.POSTGRES_DB }};"
          sudo -u postgres psql -c "CREATE USER ${{ secrets.POSTGRES_USER }} WITH PASSWORD '${{ secrets.POSTGRES_PASSWORD }}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${{ secrets.POSTGRES_DB }} TO ${{ secrets.POSTGRES_USER }};"
      - name: Use Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Test
        run: npm test
        env:
          PORT: ${{ secrets.ENV_PORT }}
          DB_NAME: ${{ secrets.ENV_DB_NAME }}
          DB_USER: ${{ secrets.ENV_DB_USER }}
          DB_PASSWORD: ${{ secrets.ENV_DB_PASSWORD }}
          HOST: localhost
          DIALECT: postgres
