name: Integration Test for User APIs

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  test:
    name: Run integration tests for users
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: cloud_assignment_db
      POSTGRES_USER: payalkhatri
      POSTGRES_PASSWORD: postgres
      HOST: localhost
      DIALECT: postgres
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U payalkhatri" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      #   - name: Wait for PostgreSQL to be ready
      #     run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - name: Run Test
        run: npm test
