name: Integration Test for User APIs

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  build:
    name: Run integration tests for users
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: cloud_assignment_db
          POSTGRES_USER: payalkhatri
          POSTGRES_PASSWORD: cloud123
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U payalkhatri" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Use Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Run Test
        run: npm test
        env:
          PORT: 3001
          DB_NAME: cloud_assignment_db
          DB_USER: payalkhatri
          DB_PASSWORD: cloud123
          HOST: localhost
          DIALECT: postgres
